### ISSUE TITLE
[Question] Option to add plugins from sub directories of Github projects

### ISSUE THREAD

**Issue by leelavg** [k-takata/minpac#103]
I've been using minpac for quite sometime now and it worked pretty well as a plugin manager. However, is there any option to add/pull specific directories under a Github project, like in [vim-plug (rtp)](https://github.com/junegunn/vim-plug/#plug-options)?

I faced this issue while installing [yapf](https://github.com/google/yapf/tree/master/plugins).

Thanks in advance.

**Comment by k-takata** [comment]
This was discussed in #33 and now implemented in #99.
I haven't released this yet, but you can try this by using the `devel` branch.

**Comment by leelavg** [comment]
Thanks for speedy response and pardon for not checking earlier issues.
