### ISSUE TITLE
Is `minpac#add` required in .vimrc?

### ISSUE THREAD

**Issue by mralusw** [k-takata/minpac#105]
Currently, I'm installing all plugins with `minpac#add (…, {'type': 'opt'})` from vim. My .vimrc contains only
``` 
packadd  minpac
call  minpac#init()
```
No other plugins are mentioned in .vimrc at all. When needed, I load plugins by manually typing `:packadd plugin-name` in vim.

Is this workflow ok? The documentation seems to always talk about loading plugins in .vimrc with `minpac#add`, except in a single passage:
```
"opt" plugins can be loaded with :packadd command
```

**Comment by k-takata** [comment]
If you just execute `call minpac#add (…, {'type': 'opt'})` from the command line manually, then `minpac#update()` will install or update the plugins just you typed. If you didn't call `minpac#add()` for some plugins, the plugins won't be updated, and if you call `minpac#clean()`, the plugins will be deleted.

**Comment by mralusw** [comment]
Yes, I always do `#add()` and (forgot to mention) `#update()` from the vim command line, then `packadd` as necessary.

Can I leave it at that? Do I *have* to copy the `#add()` commands to my `$MYVIMRC`? This is not clear from the documentation, and there seem to be some benefits to "registering" plugins in .vimrc

**Comment by k-takata** [comment]
> Can I leave it at that?

It's okay if you really understand what you are doing (and how minpac is working).
However, using minpac without registering plugins in .vimrc is not intended at all, so I won't write such usage in the document.
Is there any reason you don't want to add `minpac#add` in .vimrc?

**Comment by mralusw** [comment]
It's a simpler workflow for me to just experiment with `:call #add/#update` + `packadd`.

The problem is that all this talk of "registering" plugins in the Minpac documentation seems to imply there's some mysterious magic that Minpac performs behind the scenes, separately from the simple and clear logic of the packadd built-in.

I don't really want any magic when *loading*, that's why I chose the packadd way in the first place. I do like Minpac for installing/updating plugins. After they are installed though, I don't want to depend on anything but pure Vim (i.e. packadd)

Anyway, thanks for your great work. I find Minpac very useful and convenient.

**Comment by k-takata** [comment]
`#add()` just adds the information (name, URL, etc.) of a plugin to an internal list used by minpac.
The internal list is needed when you use `#update()` or `#clean()`.
`#add()` won't load any plugin regardless of whether the type is 'start' or 'opt'.
It's Vim's task to load plugins, and minpac has nothing to do with loading them. The 'start' plugins are loaded at startup, and the 'opt' plugins are loaded only when packadd is used. There's no *magic* here.

If you don't want `#add()` to be called every time when you execute Vim, I recommend this:
https://github.com/k-takata/minpac/tree/be97b16c7ecd26e0a2426aa1dd23e6517802213b#load-minpac-on-demand
