### ISSUE TITLE
Loading prabirshrestha/asyncomplete-buffer.vim using minpac

### ISSUE THREAD

**Issue by slashmili** [k-takata/minpac#106]
Hi, 

When I try to load `prabirshrestha/asyncomplete-buffer.vim` using 
```
call minpac#add('prabirshrestha/asyncomplete-buffer.vim')
```

looks like the the plugin is not loaded. I know that because I made a change that would have been a syntax error but neovim opens without any error.

For now I'm using to load the plugin manually
```
source /home/user/.config/nvim/pack/minpac/start/asyncomplete-buffer.vim/autoload/asyncomplete/sources/buffer.vim
```

I'm using 544f2e642e55a764d144e97e8fb040cebef14948 version of minpac

**Comment by k-takata** [comment]
It seems that asyncomplete-buffer.vim provides only one file `autoload/asyncomplete/sources/buffer.vim`.
It means that the file will not be automatically loaded until one of the `asyncomplete#sources#buffer#...` functions is explicitly called.
From minpac side, the plugin is correctly installed if the `asyncomplete-buffer.vim` is added in `runtimepath`. (You can check it by `:echo &rtp`.)

**Comment by slashmili** [comment]
Thanks, yes it's in `runtimepath`.

I close this issue for now
