### ISSUE TITLE
post-update hook cannot find the autoload function belonging to the plugin itself

### ISSUE THREAD

**Issue by yanzhang0219** [k-takata/minpac#107]
Hi,

I have been using this plugin manager for a long time and it is really nice. Thank you for your work in developing it. 

I tried to install a plugin for markdown preview via  `call minpac#add('iamcco/markdown-preview.nvim', {'do': 'call mkdp#util#install()'})`, but when I opened messages, I showed that this autoload function cannot be found. I think that after a new plugin is installed, its path is not added to the `runtimepath` until we restart the vim, so vim cannot find it. 

What's the right and elegant way to deal with this? 

Thank you very much. 
Best regards.

**Comment by k-takata** [comment]
Sorry for late.
How about using `:packloadall!`?
E.g. `{'do': 'packloadall! | call mkdp#util#install()'}`

**Comment by yanzhang0219** [comment]
Doesn't matter. I think `{'do': 'packloadall! | call mkdp#util#install()'}` doesn't work either. After posting this issue, I tried to install the plugin without any hook in this way `call minpac#add('iamcco/markdown-preview.nvim')`. Then I executed`:packloadall` followed by `:call mkdp#util#install()` manually. It still showed the autoload function could not be found. 

To make the hook work, I installed it via `opt` type in such a way `call minpac#add('iamcco/markdown-preview.nvim', {'type': 'opt', 'do': 'packadd markdown-preview.nvim | call mkdp#util#install()'})`. And coincidentally, `opt` makes sense for this plugin as it is only for markdown. So I just need to use `autocmd FileType markdown packadd markdown-preview.vim` to make it work in any markdown file. 

However, as for some plugin that should not be `opt`, the hook will not work when it needs to execute some autoload function belongings to this plugin itself. So I still think this is an issue. 

Thank you!

**Comment by k-takata** [comment]
> Then I executed`:packloadall` followed by `:call mkdp#util#install()` manually.

You executed `:packloadall` but not `:packloadall!`, right?
`!` does matter, I think.

> To make the hook work, I installed it via `opt` type

Ah, that might be a good choice for this case.

**Comment by yanzhang0219** [comment]
Wow, nice. Yeah, `:packloadall!` works! Thank you.

So what I understand is that minpac won't update `runtimepath` automatically after installing a plugin, right? We have to use `packloadall!` to reloads all installed plugins so far to add the newly installed plugin into `runtimepath`, and then vim could find an autoload function in it. Is my understanding correct?

Thanks.

**Comment by k-takata** [comment]
Correct.
Minpac doesn't manage `runtimepath` at all (except for executing Neovim's `:UpdateRemotePlugins` command).
Updating `runtimepath` is the task of Vim's packages feature. That's why `packloadall!` needs to be called manually.

**Comment by yanzhang0219** [comment]
Cool! I got it. Thank you very much. 
Just one more confusion, after I install a plugin tcomment_vim via `call minpac#add('tomtom/tcomment_vim')`, I don't need to relaunch vim or run any commands manually, and instead, I can comment or uncomment a line directly. It seems that this newly-installed plugin is added into `runtimepath` automatically right after it is installed. However, for that markdown-preview.nvim plugin, why do I need to relaunch vim or manually run `packloadall!`? I have not too much experience on vim and hope you could help me to make me clear. Thanks a lot.

**Comment by k-takata** [comment]
Hmm, not sure. Somehow `packloadall!` was executed?
After you install a new plugin, you need to update `runtimepath` by restarting Vim, `packloadall!` or `packadd` (for opt plugin).

**Comment by yanzhang0219** [comment]
Okay. I see. Thank you very much for your help. Closing this.
