### ISSUE TITLE
Updating blocks for a while before showing window

### ISSUE THREAD

**Issue by Luxed** [k-takata/minpac#108]
**Editor used**:

I'm using Neovim nightly (latest 0.5 build with the neovim Fedora COPR repo).

**Issue**:

Here's a little gif of how it looks like:

[![asciicast](https://asciinema.org/a/g1FRx02CdpQxA7xjiQdqocy6V.svg)](https://asciinema.org/a/g1FRx02CdpQxA7xjiQdqocy6V)

The editor blocks for a while, then suddenly shows the progress once it's almost done.

**Expected behavior**:

I would expect the window to open sooner to gradually show me the current progress on the update or installation of plugins.

**Comment by k-takata** [comment]
Could you try #110?

**Comment by Luxed** [comment]
@k-takata Unfortunately I now get an `E132: Function call depth is higher than 'maxfuncdepth'`.

**Comment by k-takata** [comment]
Ah, okay, updated.
Could you try again?

**Comment by Luxed** [comment]
@k-takata It's getting better:

[![asciicast](https://asciinema.org/a/QFlWOX88qGV8xzDAgdPWMr63k.svg)](https://asciinema.org/a/QFlWOX88qGV8xzDAgdPWMr63k)

The progress is still dumped at the end though :(
I'm so sorry about all this, I'd love to be able to fix it myself, but vimscript makes no sense to me.

**Comment by k-takata** [comment]
I merged #110, but further investigation is needed.

**Comment by Luxed** [comment]
@k-takata For now I'm happy with my configuration: `call minpac#init({'progress_open': 'none', 'jobs': 0})`, on top of that I call the status when everything is updated. Since I come from dein.nvim, I am fine with looking at `:mess` and/or the status window when everything's done.
That being said, I think we should keep this issue opened in case anyone else wants to look into what's happening.
