### ISSUE TITLE
minpac update progress window name "a"

### ISSUE THREAD

**Issue by habamax** [k-takata/minpac#123]
For some reason I started getting "a" window instead of `[minpac progress]`:

![image](https://user-images.githubusercontent.com/234774/98445626-ac1eaf80-2129-11eb-9105-15045bf3d976.png)

and then if I press `s` I get following error:

![image](https://user-images.githubusercontent.com/234774/98445645-c9ec1480-2129-11eb-9762-41fd85f9340d.png)

vim version: 8.2.1965

This doesn't happen in windows vim of the same version.

**Comment by habamax** [comment]
The issue is in this line:

https://github.com/k-takata/minpac/blob/113380ec84fdac067a0b33c06409a2de0f3070f7/autoload/minpac/progress.vim#L46

If I try to do this command on wsl vim:

    :file [minpac progress]

I get buffer named: `a`.

On the other hand:

    :file \[minpac progress\]

works.

**Comment by habamax** [comment]
![vim-minpac-issue](https://user-images.githubusercontent.com/234774/98446064-47b11f80-212c-11eb-82a7-2e6f13f20831.gif)

**Comment by habamax** [comment]
Aha!

I have a file named `a` in my home directory, and for some reason when you do `:file [minpac progress]` it names current buffer as `a`. I have removed this file and issues is gone.


But what if I need this `a` file? :)

**Comment by habamax** [comment]
> On the other hand:
> 
> ```
> :file \[minpac progress\]
> ```
> 
> works.


But not on windows.

`:h wildcards`

```
                                                wildcard wildcards
Wildcards in {file} are expanded, but as with file completion, 'wildignore'
and 'suffixes' apply.  Which wildcards are supported depends on the system.
These are the common ones:
        ?       matches one character
        *       matches anything, including nothing
        **      matches anything, including nothing, recurses into directories
        [abc]   match 'a', 'b' or 'c'
```

**Comment by habamax** [comment]
So the issue is that buffer name `[minpac progress]` is a wildcard that would match files: `m`, `i`, `n`, `p`, `a`, `c`, `r`, `o`, `g`, `e`, `s`.

* obvious solution is *not* to have those kind of files in your current working directory :)
* a better solution would be to rename `[minpac progress]` to smth else, like `minpac progress`, or `__minpac_progress__` or smth else.
* the same should be probably also done to a status window `[minpac status]`.

**Comment by habamax** [comment]
Another option would be to replace `exec` with backtick expansion (```:h `=```):

     " exec "silent file" l:bufname
     silent file `=l:bufname`

Works for me both on wls debian and windows

**Comment by k-takata** [comment]
Thank you for investigating the issue.
