### ISSUE TITLE
Inaccurate documentation of minpac#init() function

### ISSUE THREAD

**Issue by zendradix** [k-takata/minpac#129]
In the vim help page, it looks like the argument to minpac#init() should be a dictionary in a list:
https://github.com/k-takata/minpac/blob/093f00891aeb04e98ceb5a541885d025c9fae169/doc/minpac.txt#L253
Taking this literally, for example `call minpac#init([{}])`, results in `E712: Argument of extend() must be a List or Dictionary`.

The correct behaviour seems like the argument should just be a dictionary - e.g. `call minpac#init({})` runs fine.

**Comment by k-takata** [comment]
`[]` means that the item inside it can be omitted.
This notation is also used in the official help of Vim.

**Comment by zendradix** [comment]
Oh, sorry. Thank you for the clarification.
