### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by sitharah** [k-takata/minpac#147]
Hi, I migrated back from neovim to vim becuase of some reasons. and I want to know is this plugin manager still maintained or not? if not then anyone can make a plugin manager for vim? like packer.nvim? I would love to support . vim9script is faster than lua... and neovim is not an editor now.. its devs are making it like a dream viewer..built in lsp and remote connection features and even more are being added to neovim which will soon be an ide...rather than a text editor....Vim is old and old is gold....

**Comment by k-takata** [comment]
Recently I haven't updated this because I think it is matured. It works well in my environments and it has enough features for me.

Feature requests, bug reports and PRs are still welcome. However, not all the requests will be accepted because I want to keep minpac minimal.

**Comment by sitharah** [comment]
@k-takata can you convert its vimcript to vim9script? it will be a big help.. also can you tell whether you use vim or neovim? and vim config or lua config? just want to know

**Comment by sitharah** [comment]
@k-takata is it converted to vim9script?

**Comment by k-takata** [comment]
I only use Vim, however, I'm not going to drop support for Neovim. So, converting it to vim9script it not an option at this moment.
Also, minpac doesn't do heavy computation with Vim script. I'm not sure it is worth to convert to vim9script.

**Comment by sitharah** [comment]
@k-takata ok thats good because  i also use vim from now on ..Neovim is not worth to use  ...

**Comment by sitharah** [comment]
@k-takata i think converting to vim9script is not bad...

**Comment by k-takata** [comment]
minpac supports on-demand loading.
https://github.com/k-takata/minpac#load-minpac-on-demand
When it is used, converting to vim9 script doesn't have any effects on startup.
I don't want to maintain two versions: the legacy vim script version and the vim9 script version.
Closing for now.
