### ISSUE TITLE
Add more test environments

### ISSUE THREAD

**Issue by k-takata** [k-takata/minpac#21]
E.g.

* macOS on Travis CI
* Cygwin on AppVeyor
* Neovim on Linux on Travis CI

**Comment by bstaletic** [comment]
Isn't macOS on Travis just a matter of adding the following to the `.travis.yml`?
```yml
os:
  - linux
  - osx
```

**Comment by k-takata** [comment]
It's not enough, because minpac requires Vim 8.

**Comment by equal-l2** [comment]
Hello.

You can use Homebrew(`brew`) to install Vim8 on macOS.
Fortunately, Travis CI has builtin support for `brew`, so you can install Vim8 with this command.
```
brew install vim
```

You can also install Neovim in the same manner.

**Comment by k-takata** [comment]
> * Cygwin on AppVeyor

Cygwin Vim doesn't work well on AppVeyor.
