### ISSUE TITLE
is it possible to disable (and possibly clean an existing plugin)?

### ISSUE THREAD

**Issue by chrisbra** [k-takata/minpac#22]
Hi Ken,
great plugin! However I have one usage question.
I have this in my .vimrc:
```viml
packadd minpac
call minpac#init()
call minpac#add('vim-airline/vim-airline')
call minpac#add('vim-airline/vim-airline-themes')
call minpac#add('morhetz/gruvbox')
call minpac#add('bling/vim-bufferline')
command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update()
command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
packloadall
```

Is there a possibility to disable e.g. bling/vim-bufferline (and also to remove its directory completly)?
I tried using `call minpac#clean('bling/vim-bufferline')` but that did not work, so I had to quit Vim and delete the directory manually (and uncomment that section in vimrc).

Thanks for considering.

**Comment by k-takata** [comment]
A normal way is commenting out the line `call minpac#add('bling/vim-bufferline')`, reload `.vimrc`, then `call minpac#clean()`.
Or you can remove the plugin by `call minpac#clean('vim-bufferline')` without commenting out the setting. `bling/` is not needed here (similar to `:packadd`).

**Comment by chrisbra** [comment]
I see, I was confused and thought that `minpac#clean()` takes the same argument as `minpac#add()` does. It obviously doesn't. Thanks for the quick update (perhaps `clean()` should give a warning if a url has been provided?, not sure if this can be correctly detected).

**Comment by chrisbra** [comment]
I guess this was clearly a user problem, so closing.

**Comment by k-takata** [comment]
Maybe it's better to accept 'user/plugin_name' style.
