### ISSUE TITLE
Call :UpdateRemotePlugins in minpac#update() on Neovim

### ISSUE THREAD

**Issue by brglng** [k-takata/minpac#37]
I think it would be better that `minpac#update()` calls `:UpdateRemotePlugins` on Neovim, though I can do it by myself. Thanks.

**Comment by k-takata** [comment]
I don't use Neovim, so I don't know about the `:UpdateRemotePlugins` command.
What does the command do?

How about the following command?

```vim
call minpac#update('', {'do': 'UpdateRemotePlugins'})
```

**Comment by brglng** [comment]
Yes, that will work. I just think it is better to do it inside `minpac#update()`, as it is always a must-do on Neovim, just like `:helptags ALL`.

**Comment by k-takata** [comment]
Hmm, it failed on Neovim.
https://travis-ci.org/k-takata/minpac/jobs/263525029
Any idea?

**Comment by brglng** [comment]
This seems to be related with `--noplugin`. I tried on my machine and neovim does not have `:UpdateRemotePlugins` when started with `--noplugin`.

**Comment by k-takata** [comment]
Ah, okay. I will add checking for existence of the command.

**Comment by k-takata** [comment]
Please try the latest commit.

**Comment by brglng** [comment]
Thanks!

**Comment by jsfaint** [comment]
It looks this hook not work on my side

A fresh installation, 36 plugins was installed, a empty rplugin.vim was generated, but the remote plugins was not registered.
![image](https://user-images.githubusercontent.com/571829/33410067-78ae05ba-d5b9-11e7-87cc-90b7cbdef23d.png)

Maybe on the time `UpdateRemotePlugins` was called, these plugin were not sourced yet?

**Comment by k-takata** [comment]
Sorry for the late response.
`call minpac#update()` doesn't source any plugins. Plugins are sourced at start up of Vim or when you load it manually by `:packadd <plugin>`, etc.
Does `UpdateRemotePlugins` work only when plugins are sourced?

**Comment by jsfaint** [comment]
Thanks for the reply
Yes, the plugin must be sourced first.
Maybe minpac need to run `:packloadall` before run `UpdateRemotePlugins`?

**Comment by k-takata** [comment]
I don't want to load all plugins after `minpac#update()`.
Currently I don't have a good idea for this.
Maybe, defining your own command is a good way? E.g.:

```vim
command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update() | packloadall | UpdateRemotePlugins
```

(untested)

Do opt plugins also need to be loaded when executing `UpdateRemotePlugins`? If so, this might be not enough, because `packloadall` doesn't load opt plugins.

**Comment by jsfaint** [comment]
Thanks for your clarify.
But this didn't works for me, maybe because `call minpac#update()` is async.
In this command chain, when `UpdateRemotePlugins` was called, the `minpac#update()` is still in progress

**Comment by k-takata** [comment]
> But this didn't works for me, maybe because call minpac#update() is async.

Oops, I forgot that.
BTW, I try a new approach. See #47.

**Comment by jsfaint** [comment]
I tried the `nvim-rplugin` branch, but when I run `:PackUpdate` command, it shows the error below:
![image](https://user-images.githubusercontent.com/571829/34649099-e62fdbe4-f3e2-11e7-963a-d0c4cf2bcc9d.png)

**Comment by k-takata** [comment]
Oh, sorry.
Could you try again?

**Comment by jsfaint** [comment]
It works now 👍 
Thank you @k-takata

**Comment by k-takata** [comment]
Thank you for testing.
