### ISSUE TITLE
Switch from Vundle to minpac

### ISSUE THREAD

**Issue by canaaerus** [k-takata/minpac#40]
First of all let me say, that the switch from Vundle to minpac went astonishingly well.

Note that after doing the general setup of `minpac`, as well as `mv ~/.vim/bundle ~/.vim/pack/minpac/start` and replacing `Plugin 'pluginname'` with `call minpac#add('pluginname')`, I got several errors saying "Cannot specify the plugin name", which was quite confusing. So I replaced the error message in the minpac code with:

    echoerr 'Cannot extract the plugin name. (' . a:plugname . ')'

It turns out Vundle supports plugins from http://vim-scripts.org/vim/scripts.html, just be giving a name containing no slash, but minpac does not. As a solution, I used the github version under the `vim-scripts/pluginname`.

I think this (and maybe other?) error message needs to more descriptive. Also a section in the readme about switching from Vundle might be helpful for the uninitiated.

**Comment by k-takata** [comment]
> echoerr 'Cannot extract the plugin name. (' . a:plugname . ')'

I will use this error message for now. If you have a better suggestion, please let me know.

FYI, other plugin manager vim-plug and dein.vim had supported the implicit `vim-scripts`, however they dropped it recently:
https://github.com/junegunn/vim-plug/commit/f7e6a86807a1f0be7257620a8c425e1a32f877bb, https://github.com/Shougo/dein.vim/commit/54dd253d49ed17a9beb69177f70a567038b9ba3f

**Comment by canaaerus** [comment]
Thank you for your lightning fast response. I think this error message is ok now. If I encounter any other confusing ones in the future, I will let you know :-)
