### ISSUE TITLE
Some plugins are not loaded properly?

### ISSUE THREAD

**Issue by ahmedelgabri** [k-takata/minpac#43]
I'm using https://github.com/pangloss/vim-javascript for JavaScript

And here is a file using `minpac` to load the plugin vs `vim-plug`

Loaded with `minpac`
<img width="1680" alt="screen shot 2017-11-26 at 19 18 21" src="https://user-images.githubusercontent.com/63876/33243074-206c111c-d2df-11e7-98a7-a46e6a8c1640.png">

Loaded with `vim-plug`
<img width="1680" alt="screen shot 2017-11-26 at 19 19 17" src="https://user-images.githubusercontent.com/63876/33243075-2080dcd2-d2df-11e7-8504-882b81c3d4dc.png">

And here is a minimal setup that I tried

```vim
set packpath^=~/.vim
silent! packadd minpac

if !exists('*minpac#init')
  finish
endif

call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
call minpac#add('pangloss/vim-javascript')
```
Any idea what might cause this issue?

**Comment by Snaptags** [comment]
This does seem to affect other file type plugins, too. I have similar problems when trying to load
https://github.com/OrangeT/vim-csharp
or
https://github.com/mxw/vim-jsx

**Comment by Snaptags** [comment]
Im my case it was kind of a stupid user error. I still had a „syntax“ folder in my .vim folder containing a javascript.vim file just overwriting anything vim-javascript or vim-jsx tried to add 🤦‍♂️

**Comment by ahmedelgabri** [comment]
I don't have a syntax folder in my [setup](https://github.com/ahmedelgabri/dotfiles/tree/master/vim/.vim) at all and still can't get this to work

**Comment by ahmedelgabri** [comment]
@k-takata any pointers on how to debug or fix this?

**Comment by k-takata** [comment]
Sorry for the late response. I haven't tried it by myself yet.
Actually, minpac doesn't manage the 'runtimepath'. It just use Vim 8's packages feature.
I suspect whether it is a problem of Vim itself.
Does the plugin work with the packages feature without minpac?
E.g. Backup your `.vimrc` and `.vim/`, create a clean `.vim/`, then

```
git clone https://github.com/pangloss/vim-javascript.git ~/.vim/pack/test/start/vim-javascript
```

**Comment by ahmedelgabri** [comment]
@k-takata I don't think it's a `minpac` issue, I guess it's a loading order issue, it seems that the native `packages` feature loads files in a different order than `vim-plug` & that is what causing this issue. You can check my comment here https://github.com/pangloss/vim-javascript/issues/1080#issuecomment-352418599 & if you have any ideas how to fix this please let me know. 

Thanks!
