### ISSUE TITLE
runtimepath only including certain 

### ISSUE THREAD

**Issue by GodefroyClair** [k-takata/minpac#45]
Hi, 
Using nvim on Mac (see config below)with last version of minpac, my runtimepath only includes the plugin installed with minpac that start with the prefix "vim" ? Any idea why ?
I check my ~/.config/nvim/pack/minpac/start all the plugins are there but only those like "vim-textobj-entire", "vim-surround", "vimproc" are referenced in my runtimepath when I do `:set runtimepath?`
thx,
Godot
 
           -----------------------------------------------------------------

NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"

**Comment by k-takata** [comment]
Does it occur with a minimal `.vimrc` (`init.vim`)?

**Comment by k-takata** [comment]
Not enough information. Closing.
