### ISSUE TITLE
Error while updating "minpac".  Error code: 129

### ISSUE THREAD

**Issue by gbatra-xilinx** [k-takata/minpac#49]
I'm setting up minpac on a fresh neovim installation

Here's my init.vim:
```vim
packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
```
When I source the init.vim and run `:call minpac#update()` I get the following error:
> Error while updating "minpac".  Error code: 129

neovim version:
> NVIM v0.2.3-610-ga6052c7
> Build type: Release
> LuaJIT 2.0.5

`:checkhealth` output
[checkhealth.txt](https://github.com/k-takata/minpac/files/1713527/checkhealth.txt)

**Comment by k-takata** [comment]
Sorry for the late response.

> Error while updating "minpac". Error code: 129

This message is shown when the git command returns the error code 129, but I don't know what does it mean.
Do you see any other messages? Does `:mes` show anything else?

**Comment by k-takata** [comment]
Sorry for the late response.

Could you try changing the verbose option to 2 (or 3)?

```vim
call minpac#init({'verbose': 2})
```

**Comment by k-takata** [comment]
Now the default value of the 'verbose' option is changed to 2.
I hope that useful information is shown by that.

**Comment by k-takata** [comment]
Closing for now.

**Comment by xudalin0609** [comment]
If git version is lower than 1.9 this error will happen.
Update git version will solve this error

**Comment by k-takata** [comment]
Git 1.9 or later is required: https://github.com/k-takata/minpac#requirements
