### ISSUE TITLE
Error E518 when installing plugins

### ISSUE THREAD

**Issue by foxbunny** [k-takata/minpac#50]
Up until a while ago, minpac worked pretty well. Today, it started giving me `E518` for all new plugins. (I could not copy the error message so here's a screenshot.)

![image](https://user-images.githubusercontent.com/65413/36343574-36f19446-140e-11e8-9fb9-3dda7a7852a0.png)

My `nvim` directory is located within a path that has a pace in it: `C:\Users\Hajime Yamasaki\AppData\Local\nvim`. It looks like it doesn't like the space.

The plugin files are correctly checked out at an appropriate location, and plugin does work after restarting NeoVim.

**Comment by k-takata** [comment]
Sorry for the late response. I hope this is fixed by the latest commit.
