### ISSUE TITLE
FYI: My modifications to install into different packages

### ISSUE THREAD

**Issue by meldavis** [k-takata/minpac#52]
First, thanks for sharing a great plugin. 

**As an FYI:**
For my own purposes, I modified it to so it would fit in my workflow. Mainly, so it would install plugins into different packages. So that I could understand the code, I retyped/restructured/renamed it.   I renamed it not to take credit, but to keep me straight.  

The structural changes are such that a a pull request simply is not feasible.

If you want to see the changes:  https://github.com/meldavis/autopac

Thanks again. Mel.

**Comment by k-takata** [comment]
I added a link to autopac in the document.
