### ISSUE TITLE
Is there a way to unload a plugin?

### ISSUE THREAD

**Issue by antaed** [k-takata/minpac#54]
I have an [issue with a plugin](https://github.com/pangloss/vim-javascript/issues/1094) so I only load it when necessary with :packadd. A more convenient way would be to do the opposite, because the issue only occurs in certain scenarios. Is there a command I could use to unload the plugin without having to restart Vim? Thanks :)

**Comment by k-takata** [comment]
Unfortunately there are no such ways. Vim doesn't provide such kind of features.
It might be possible to delete functions, unmap key bindings, unlet variables and etc. manually, but it depends on the plugins.

**Comment by antaed** [comment]
Understood, thanks again for the reply.
