### ISSUE TITLE
Arbitrarily Opens the ssh dialog with MacVim.

### ISSUE THREAD

**Issue by yossan** [k-takata/minpac#57]
`call minpac#update()`  opens the following ssh input dialog.

![screen shot 2018-07-16 at 13 57 22](https://user-images.githubusercontent.com/11131732/42743774-1d7ba7e0-8902-11e8-9709-3d41e8602137.png)

This issue occurs when '.git' is included in the name as shown below.

```vimrc
call minpac#add('tpope/vim-projectionist.git')
```

But this doesn't occur.

```vimrc
call minpac#add('tpope/vim-projectionist')
```

Thank you for creating great this plugin.

**Comment by k-takata** [comment]
Minpac automatically adds the '.git' suffix.
If `user/repo.git` is specified, minpac tries to access `https://github.com/user/repo.git.git`. If the URL doesn't exist, the dialog will be opened.
This is an expected behavior. I will update the documents.
