### ISSUE TITLE
Paging `echom` interrupts jobs 

### ISSUE THREAD

**Issue by nelstrom** [k-takata/minpac#6]
I've recorded a screencast demonstration:

![minpac-paged-updates](https://cloud.githubusercontent.com/assets/7069/24525422/19a957c8-1592-11e7-90bf-3aa613719113.gif)

To reproduce:

1) `rm -rf ~/.vim/pack/minpac/start`
1) launch vim
1) run `:call minpac#update()`

In this demo, I've got 44 plugins being cloned into the `start` directory (plus a few more in the `opt` directory). My terminal window is 22 lines tall, allowing for 20 or so messages to be printed by `echo` or `echom` before the `-- More --` prompt appears. It seems as though `minpac` stalls while the `-- More --` prompt is visible. When I press the space bar, the `-- More --` prompt disappears and the next page of messages fills the screen, allowing the `minpac` jobs to continue until the screen fills up again, and so on...

The same thing happens both in `vim` and `nvim`. (I used `nvim` for this screencast, in part to demonstrate that #3 is fixed)

**Comment by nelstrom** [comment]
I think it's neat that you can review the results of running `:call minpac#update()` just by running:

    :messages

It would be a shame to lose that feature.

I wonder if this issue with paging could be avoided by building a list of messages as the jobs are running. Then when all jobs have completed, use `echom` to output them all at once.

**Comment by justinmk** [comment]
This is a known (intentional) limitation of nvim. 

Fun trivia: jobs actually _are_ processed during `getchar()`, but not most other wait-for-input scenarios ("press enter", 'more' prompt, `g`, ...). 

> My terminal window is 22 lines tall, allowing for 20 or so messages to be printed by echo or echom before the -- More -- prompt appears. 

minpac could temporarily set `'nomore'` to disable the pager.

**Comment by nelstrom** [comment]
@justinmk good idea! I've recorded a new screencast where I run:

    :set nomore
    :call minpac#update()

This time the jobs don't appear to be paused.

![minpac-continuous-updates](https://cloud.githubusercontent.com/assets/7069/24529216/4c595992-15a2-11e7-9375-5997c163104e.gif)

**Comment by kristijanhusak** [comment]
@k-takata is there way to avoid the same issue when running post hooks?
For example, adding package like this causes it:

```vimL
call minpac#add('w0rp/ale', { 'do': '!npm install -g prettier' })
```

**Comment by k-takata** [comment]
How about using the `minpac#job#start()` function? e.g.
```vim
call minpac#add('w0rp/ale', { 'do': {-> minpac#job#start('npm install -g prettier') }})
```
(not tested)
