### ISSUE TITLE
Update plugin after changing branch in config

### ISSUE THREAD

**Issue by EgZvor** [k-takata/minpac#63]
Let's say I have a following line in my `vimrc`
```
call minpac#add('EgZvor/dracula-vim')
```
I install the plugin, but then find out that I needed to specify a branch. So I change the config to:
```
call minpac#add('EgZvor/dracula-vim', {'branch': 'draculasplit'})
```
However after calling `minpac#update` nothing will happen, because it only checks if a plugin directory exists.

**Comment by k-takata** [comment]
Please use `{'rev': 'draculasplit'}` instead.
For detail, see this: https://github.com/k-takata/minpac/blob/9dd30a7030e7caffedb9e7ba14331ef24f1ddb81/doc/minpac.txt#L332-L345

**Comment by EgZvor** [comment]
Ok, thanks, that makes sense.
