### ISSUE TITLE
helptags fails to run properly

### ISSUE THREAD

**Issue by annagrram** [k-takata/minpac#75]
The glob pattern in `s:is_helptags_old` uses the {} alternation pattern which doesn't seem to be supported by glob.
I tried to search the documentation and tried with both vim8 and neovim but with no success.
The glob function just returns an empty list.

I solved the problem by splitting the alternation like:
`let l:txts = glob(a:dir . '/*.txt', 1, 1) + glob(a:dir . '/*.[a-z][a-z]x', 1, 1)`

Am I missing something?

**Comment by k-takata** [comment]
Which OS and which version of Vim do you use?
I confirmed that it works on Windows and Linux.

**Comment by annagrram** [comment]
Debian sid
Neovim v0.3.4
Vim 8.1.948

**Comment by k-takata** [comment]
Hmm, strange. It should work on that environment.
Doesn't `:echo glob('*.{c,h}', 1, 1)` work when you execute this on some source code directory?
It should return as the same result as `:echo glob('*.[ch]', 1, 1)`.

**Comment by annagrram** [comment]
`:echo glob('*.[ch]', 1, 1)` returns the correct result.
`:echo glob('*.{c,h}', 1, 1)` returns an empty list.

**Comment by annagrram** [comment]
Another input.
I use the fish shell.
When I invoke Neovim (or Vim) with `env SHELL=/bin/shell vim` it works properly.
I'm not sure how (Neo)vim decides what is supported by glob, because fish does support {}, but it seems to be broken in that shell.

**Comment by k-takata** [comment]
Thank you for the information. It seems better to avoid using {} in glob().
I have updated as you suggested.

**Comment by annagrram** [comment]
Thank you very much for the quick fix!
