### ISSUE TITLE
E121 when updating plugins

### ISSUE THREAD

**Issue by bennyyip** [k-takata/minpac#77]
Calling minpac#update occasionally fails with following error message:
```
Error detected while processing function minpac#update[2]..minpac#impl#update[35]..<SNR>190_update_single_plugin[54]..<SNR>190_check_plugin_status[2]..minpac#impl#get_plugin_revision[1]..<SNR>190_exec_plugin_cmd[3]..minpac#impl#system:
line   11:
E121: Undefined variable: l:ret
```
`minpac#impl#system` doesn't always assign value to `l:ret`:
https://github.com/k-takata/minpac/blob/a6cdb392e58e8cc65af01bf2366d3c3e4ab34f33/autoload/minpac/impl.vim#L66-L78

**Comment by k-takata** [comment]
Thank you for reporting. Fixed.
