### ISSUE TITLE
`minpac#update()` produces too many messages

### ISSUE THREAD

**Issue by nelstrom** [k-takata/minpac#8]
I find it a bit confusing when `minpac#update()` mentions each plugin twice. For a new plugin, we get `Cloning vim-plugin` followed by `Updated vim-plugin`. For a plugin that's already installed, we get `Updating vim-plugin` followed by `Updated vim-plugin`. 

![verbose-output](https://cloud.githubusercontent.com/assets/7069/24603932/b6d30ff6-185a-11e7-88ff-dd6084eb020f.png)

Perhaps these messages are useful when developing `minpac`, but as a minpac user I'd prefer it if the output from `minpac#update()` was less verbose. I'd suggest removing the `echo` statements, and keeping only the `echom` statements. (Or if the `echo` statements are useful, maybe only enable them with a `verbose` option?)

**Comment by k-takata** [comment]
> Or if the echo statements are useful, maybe only enable them with a verbose option?

Maybe we can add a `verbose` option to `minpac#init()`.

**Comment by nelstrom** [comment]
I can think of three things that might happen to a plugin after running `minpac#update()`:

1) the plugin is installed for the first time
2) the plugin is updated
3) nothing happens, because the plugin is already up to date

It would be nice if the output from `minpac` could include this information. In the first case, it could say `Installed vim-plugin`. In the second case, it could say `Updated vim-plugin` (as is currently the case). The third case depends on issue #9. My preference in this case would be to output no message at all. That way, you would only see messages where something actually happened.

**Comment by k-takata** [comment]
> Maybe we can add a verbose option to minpac#init().

Added.

> It would be nice if the output from minpac could include this information.

Agree.

**Comment by k-takata** [comment]
Updated. Please try.

**Comment by nelstrom** [comment]
I've tried this in both Vim8 and NeoVim and it works nicely. Here's a screencast showing it in neovim:

![minpac-quiet-output](https://cloud.githubusercontent.com/assets/7069/24697766/3fb89e94-19e6-11e7-8669-90ecfee350c9.gif)

In the case where there's nothing to update, the only message you see is `Finished`, which doesn't make a lot of sense by itself. Maybe it should say `All plugins are up to date` or something like that?

**Comment by k-takata** [comment]
Okay, updated.

**Comment by nelstrom** [comment]
@k-takata you've gone the extra mile with [this commit](https://github.com/k-takata/minpac/commit/13630449a9059709533ec456bcf53f353e75e444)! I had meant to suggest that in all cases, the message `Finished` could be replaced with `All plugins are up to date`. It's even better how you've done it. :)

**Comment by k-takata** [comment]
Hahaha, now I understand your intention. :-)
Then I go one more further step.
I changed the message to show the number of updated plugins.

**Comment by nelstrom** [comment]
@k-takata can you send me an email at drew@vimcasts.org? There's something I'd like to show you. (I'll delete this comment after receiving your email)

**Comment by k-takata** [comment]
The original issue has been already fixed. So closing.
