### ISSUE TITLE
how to install vim-prettier with the option "do:yarn install"?

### ISSUE THREAD

**Issue by acuteapple** [k-takata/minpac#80]
I have installed yarn。Vim shows "yarn install" isn't the commander of editor.

**Comment by k-takata** [comment]
Try `{'do': 'silent! !yarn install'}` or `{'do': {-> system('yarn install')}}`.
The 'do' option must be an Ex command or a Funcref.

**Comment by acuteapple** [comment]
Thanks a lot!
