### ISSUE TITLE
Neovim/deoplete: problem with calling a plugins function

### ISSUE THREAD

**Issue by benjaminbauer** [k-takata/minpac#82]
Hi @k-takata, thanks for this minimal plugin manager! Unfortunately I failed to setup deoplete with it. I think it is unrelated to https://github.com/k-takata/minpac/issues/37, since for me it seems to fail much earlier, namely when trying to configure the plugin. Is my config wrong? Is this a bug?

I stripped my init.vim down to this:
```
function! PackInit() abort
  packadd minpac

  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  call minpac#add('Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' })
endfunction

command! PackUpdate call PackInit() | call minpac#update()
command! PackClean  call PackInit() | call minpac#clean()
command! PackStatus call PackInit() | call minpac#status()

call deoplete#custom#option('sources', {
    \ 'python': ['LanguageClient'],
    \})
```

After calling `:PackUpdate`, which confirms the succesfull installation, when I open neovim I get:
```
Error detected while processing /home/benni/.config/nvim/init.vim:
line   16:
E117: Unknown function: deoplete#custom#option
```

However **when I call it from neovim it works**.

**Comment by k-takata** [comment]
Vim's packages feature adds plugin directories into 'runtimepath' after .vimrc is loaded. So you cannot normally call a plugin's function inside .vimrc.
If you want to update 'runtimepath' earlier, try using the `packloadall` command. The function may work after that.
Another idea is using the `VimEnter` autocommand to call the function. It will be triggered after .vimrc is loaded, 'runtimepath' is updated and other initialization is finished.

**Comment by benjaminbauer** [comment]
Thanks for the hint! I use the autocmd approach:
```
autocmd VimEnter * call deoplete#custom#option('sources', {
    \ 'python': ['LanguageClient'],
    \})
```
