### ISSUE TITLE
Sync finish on minpack#update()

### ISSUE THREAD

**Issue by expelledboy** [k-takata/minpac#86]
I am trying to install plugins once off in a `Dockerfile` without running vim. Previously with `vim-plug` I used the follow command to install all the plugins used in the `.vimrc`

```
vim -E -s -u "$HOME/.vimrc" +PlugInstall +qall
```

Is there anyway for me to achieve this with minpack?

I was hoping this might work

```
vim -E -s -u "$HOME/.vimrc" -c 'call minpac#update('', {'do': 'quit'})'
```

**Comment by k-takata** [comment]
It might depend on how you wrote .vimrc, but this works for me:

```
vim -Nu "$HOME/.vimrc" -c "call PackInit() | call minpac#update('', {'do': 'quit'})"
```

`-N` is needed if you don't write `set nocp` in your .vimrc.
`call PackInit()` is needed if you follow this instruction: https://github.com/k-takata/minpac#load-minpac-on-demand
