### ISSUE TITLE
tags files are not sorted on Mac 10.15 Catalina

### ISSUE THREAD

**Issue by MooersLab** [k-takata/minpac#89]
I am using minpac with vim 8.1 on Mac Catalina 10.15.1.
I have updated Xcode , removed the older commandliine tools, and reinstalled them.
I get the following error after entering :help stan-vim.

E432: Tags file not sorted: /Users/blaine/.vim/pack/minpac/start/vim-snipmate/doc/tags
E432: Tags file not sorted: /Users/blaine/.vim/pack/minpac/start/vim-airline-themes/doc/tags
E432: Tags file not sorted: /Users/blaine/.vim/pack/minpac/start/vim-airline/doc/tags
E432: Tags file not sorted: /Users/blaine/.vim/pack/minpac/start/vim-addon-mw-utils/doc/tags
E432: Tags file not sorted: /Users/blaine/.vim/pack/minpac/start/tlib_vim/doc/tags
E432: Tags file not sorted: /Users/blaine/.vim/pack/bundle/start/vim-snipmate/doc/tags
E432: Tags file not sorted: /Users/blaine/.vim/pack/bundle/start/vim-addon-mw-utils/doc/tags
E432: Tags file not sorted: /Users/blaine/.vim/pack/bundle/start/tlib_vim/doc/tags
E432: Tags file not sorted: /opt/local/share/vim/vim81/doc/tags
E426: tag not found: stan-vim@en

PackStatus does not report any issues.

I wonder if this is a Catalina isuse. 
A similar issue was reported for [Neovim](https://github.com/neovim/neovim/issues/11196).

I have attached by vimrc and packages.vim files.
[vimrc.txt](https://github.com/k-takata/minpac/files/3965358/vimrc.txt)
[packages.vim.txt](https://github.com/k-takata/minpac/files/3965361/packages.vim.txt)

**Comment by k-takata** [comment]
This was a bug of Vim on Catalina and fixed with [8.1.2152](https://github.com/vim/vim/commit/27fc8cab227e30f649f52e74efd58ad56d21e9bb). Please use a newer version of Vim.

**Comment by MooersLab** [comment]
Thank you! I was using an earlier version from macports which is still outdated. I installed vim 8.2.0 with homebrew and the help is now working.
