### ISSUE TITLE
Better update check

### ISSUE THREAD

**Issue by k-takata** [k-takata/minpac#9]
Currently minpac shows a message `Updated: <plugin-name>` when `git pull` succeeds.
This means that the message is shown even the plugin is not actually updated.
The `:helptag` command is also executed at the same time.

Is there a good way to check if a plugin is actually updated?
Perhaps `git rev-parse HEAD` should be used before and after `git pull`?

**Comment by nelstrom** [comment]
[This SO answer](http://stackoverflow.com/a/3278427/128850) has some good info. I don't suppose `minpac` needs to care about such scenarios as `"Need to push"` or `"Diverged"`, but the `"Up-to-date"` and `"Need to pull"` scenarios are relevant.

**Comment by k-takata** [comment]
Thank you for the information.
It seems that it also uses `git rev-parse`.

**Comment by k-takata** [comment]
Fixed.
