### ISSUE TITLE
Proper way to install plugins with a function from that plugin

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [k-takata/minpac#95]
I have read through the issues and from my understanding the vim's package manager works is newly installed plugins aren't added into runtime until the next time vim is opened.

Is there any way to reload the runtime or anyway to use that plugins function without exiting vim?

**Comment by NilsIrl** [comment]
This is a problem in firenvim: https://github.com/glacambre/firenvim#pre-built

**Comment by NilsIrl** [comment]
We found a solution for firenvim: https://github.com/glacambre/firenvim/blob/f47791f01a215b6722d426d0cf697b96e383d5d9/README.md#pre-built

I don't think there is any acceptable fix here. The best solution so this "workaround".

**Comment by ahmedelgabri** [comment]
@Th3Whit3Wolf this might be useful for you https://github.com/k-takata/minpac/issues/74#issuecomment-462643066

**Comment by Th3Whit3Wolf** [comment]
**Workaround** as discussed by @NilsIrl [here](https://github.com/glacambre/firenvim/pull/319)

``` vim
call minpac#add('pluginauthor/plugin', { 'type': 'opt', 'do': 'packadd plugin | call plugin#function()'})
```

Obvious short comings of this approach is that this means you _**must**_ load the plugin on its own or setup an autoload function.

If you need the plugin on (neo)vim startup then I recommend add this to your vimrc

```vim
autocmd VimEnter * packadd plugin
```

**Comment by NilsIrl** [comment]
> If you need the plugin on (neo)vim startup then I recommend add this to your vimrc
> 
> ```viml
> autocmd VimEnter * packadd plugin
> ```

I would just put the following in your `.vimrc`:

```vim
packadd plugin
```

**Comment by Th3Whit3Wolf** [comment]
> > If you need the plugin on (neo)vim startup then I recommend add this to your vimrc
> > ```viml
> > autocmd VimEnter * packadd plugin
> > ```
> 
> I would just put the following in your `.vimrc`:
> 
> ```viml
> packadd plugin
> ```

Yeah that's definitely the more easy obvious solution, I'm not sure why that wasn't the first thing that popped into my head
